### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by weiquanswq** [weiquanswq/SEBC#12]

**Comment by weiquanswq** [comment]
Kerberose enabled in my cluster. 
However, there is an issue running terasort as "raffles"

debug steps taken
 - able to block user from running ```hadoop fs -ls /``` without ticket 
-  able to accessit with ticket.

**Comment by weiquanswq** [comment]
```cat /etc/passwd | grep 501``` is empty 
``` cat /etc/passwd | grep raffles```  is ``` raffles : x :2700:2700::/home/raffles:/bin/bash```

**Comment by weiquanswq** [comment]
Resolved -- 
i missed out ``` -u 2700``` in my other node. 

After modifying the uid, it works

**Comment by mfernest** [comment]
Missing `pi` job.
Failed `terasort` job

INC
