### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by weiquanswq** [weiquanswq/SEBC#2]
I am setting up this Cluster in **Azure** environment

**Comment by mfernest** [comment]
Have you completed your system checks?

**Comment by weiquanswq** [comment]
I completed MySQL setup. However, after I install my cloudera-manager-server. it fails again. 
its giving me this error : 
```

2016-12-05 08:51:28 25798 [ERROR] InnoDB: Unable to lock ./ibdata1, error: 11
2016-12-05 08:51:28 25798 [Note] InnoDB: Check that you do not already have another mysqld process using the same InnoDB data or log files.
```

Are you able to advise?

**Comment by mfernest** [comment]
It would appear the system thinks you are running two `mysqld` processes. Did you by chance start it manually and the `service` or `systemctl` command?

**Comment by weiquanswq** [comment]
Issue Resolved - 
comment  the below statement in ```/etc/my.cnf```
```
#sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
```

**Comment by weiquanswq** [comment]
Cluster Installation Completed

**Comment by weiquanswq** [comment]
Local Repository Setup Completed

**Comment by mfernest** [comment]
The solution to your `ibdata` problem is non-obvious. Where did you find it?

**Comment by mfernest** [comment]
`1_preinstall.md` - good
`2_replica_working.md` - good notes
`3_cm_installed.PNG` - good
`4_local_repo.PNG` - 🏆 

Good work
