### ISSUE TITLE
Storage Lab

### ISSUE THREAD

**Issue by weiquanswq** [weiquanswq/SEBC#3]

**Comment by weiquanswq** [comment]
http://clouderasedc00.southeastasia.cloudapp.azure.com:7180/

**Comment by weiquanswq** [comment]
Regarding Resources experiment with _YARNtest.sh_ , 
I always think that having more memory for the reducer will increase the efficiency, but it is not the case in the experiment. Why is that so? 
or did I configure  something wrong?

**Comment by weiquanswq** [comment]
Lab Completed

**Comment by mfernest** [comment]
I'll address your question on the reducer in your Resources lab.

**Comment by mfernest** [comment]
🏆  - good work
