### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by weiquanswq** [weiquanswq/SEBC#6]

**Comment by weiquanswq** [comment]
Yesterday Evening, 7th Dec, I faced an issue with setting up TLS between Management service and  Certifications.  Then I managed to discovered that authentication between admin console is checked but not authentication between agent and server. After enabling it, resolved the issue. 

However, another issue arise on the diff expectation of the hostname. In the _cloudera-scm-agent/config.ini_, I specified IP address instead of the hostname. Therefore, after modifying the variable and it works totally fine. 

Next issue, is the kerberos keytab conflicts with hostname. The hostname i gave and inserted in my ```/etc/hosts/``` is in camel case, whereas in the kerberos database is in lowercase. This issue was resolved by changing the ```/etc/hosts``` to all lowercase and regenerate all keytabs for all services.

**Comment by weiquanswq** [comment]
my cluster detected 2 namenode instead of Active and Passive namenode. Trying to resolve before proceeding on to ```sentry-test.md```

**Comment by mfernest** [comment]
Pretty messy! I bet that was a lot of work to clean up.

**Comment by mfernest** [comment]
Non-renewable ticket appears in `kinit.md`

INC
